"""add_guest_stays_table

Revision ID: 140b816d43dd
Revises: c41a7a4abdd5
Create Date: 2026-03-25 20:08:14.220044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140b816d43dd'
down_revision: Union[str, Sequence[str], None] = 'c41a7a4abdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_stays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('reservation_no', sa.String(length=50), nullable=False),
    sa.Column('ota_channel', sa.String(length=50), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_name_kana', sa.String(length=100), nullable=True),
    sa.Column('guest_email', sa.String(length=200), nullable=True),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=10), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('expected', 'checked_in', 'checked_out', 'no_show', 'cancelled', name='staystatus'), nullable=False),
    sa.Column('checkin_time', sa.Time(), nullable=True),
    sa.Column('checkout_time', sa.Time(), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_stays_checkin_date'), 'guest_stays', ['checkin_date'], unique=False)
    op.create_index(op.f('ix_guest_stays_checkout_date'), 'guest_stays', ['checkout_date'], unique=False)
    op.create_index(op.f('ix_guest_stays_property_id'), 'guest_stays', ['property_id'], unique=False)
    op.create_index(op.f('ix_guest_stays_reservation_no'), 'guest_stays', ['reservation_no'], unique=False)
    op.create_index(op.f('ix_guest_stays_status'), 'guest_stays', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_stays_status'), table_name='guest_stays')
    op.drop_index(op.f('ix_guest_stays_reservation_no'), table_name='guest_stays')
    op.drop_index(op.f('ix_guest_stays_property_id'), table_name='guest_stays')
    op.drop_index(op.f('ix_guest_stays_checkout_date'), table_name='guest_stays')
    op.drop_index(op.f('ix_guest_stays_checkin_date'), table_name='guest_stays')
    op.drop_table('guest_stays')
    # ### end Alembic commands ###
