"""initial schema

Revision ID: 90b9a82014e4
Revises: 
Create Date: 2026-03-25 14:48:21.229280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b9a82014e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cm_property_code', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=True),
    sa.Column('checkin_time', sa.String(length=10), nullable=True),
    sa.Column('checkout_time', sa.String(length=10), nullable=True),
    sa.Column('website_url', sa.String(length=300), nullable=True),
    sa.Column('own_rakuten_hotel_no', sa.String(length=20), nullable=True),
    sa.Column('event_area', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('approval_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('auto_approve_threshold_levels', sa.Integer(), nullable=False),
    sa.Column('notification_channel', sa.String(length=50), nullable=False),
    sa.Column('notification_email', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('booked_rooms', sa.Integer(), nullable=False),
    sa.Column('booked_revenue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'capture_date', 'target_date', name='uq_snapshot')
    )
    op.create_index(op.f('ix_booking_snapshots_capture_date'), 'booking_snapshots', ['capture_date'], unique=False)
    op.create_index(op.f('ix_booking_snapshots_property_id'), 'booking_snapshots', ['property_id'], unique=False)
    op.create_index(op.f('ix_booking_snapshots_target_date'), 'booking_snapshots', ['target_date'], unique=False)
    op.create_table('budget_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_occupancy', sa.Float(), nullable=True),
    sa.Column('target_adr', sa.Integer(), nullable=True),
    sa.Column('target_revpar', sa.Integer(), nullable=True),
    sa.Column('target_revenue', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'year', 'month', name='uq_budget_target')
    )
    op.create_index(op.f('ix_budget_targets_property_id'), 'budget_targets', ['property_id'], unique=False)
    op.create_table('comp_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('expedia_hotel_id', sa.String(length=50), nullable=True),
    sa.Column('expedia_url', sa.String(length=500), nullable=True),
    sa.Column('rakuten_hotel_no', sa.String(length=50), nullable=True),
    sa.Column('google_place_id', sa.String(length=200), nullable=True),
    sa.Column('tripadvisor_location_id', sa.String(length=50), nullable=True),
    sa.Column('scrape_mode', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('competitor_name', sa.String(length=200), nullable=False),
    sa.Column('room_type_label', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('available_rooms', sa.Integer(), nullable=True),
    sa.Column('plans_available', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('rakuten_no', sa.String(length=20), nullable=True),
    sa.Column('is_own_property', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('service_score', sa.Float(), nullable=True),
    sa.Column('location_score', sa.Float(), nullable=True),
    sa.Column('room_score', sa.Float(), nullable=True),
    sa.Column('equipment_score', sa.Float(), nullable=True),
    sa.Column('bath_score', sa.Float(), nullable=True),
    sa.Column('meal_score', sa.Float(), nullable=True),
    sa.Column('extra_scores', sa.String(length=500), nullable=True),
    sa.Column('user_review', sa.String(length=2000), nullable=True),
    sa.Column('review_url', sa.String(length=500), nullable=True),
    sa.Column('review_date', sa.String(length=30), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'hotel_name', 'source', name='uq_rating_prop_hotel_source')
    )
    op.create_index(op.f('ix_competitor_ratings_property_id'), 'competitor_ratings', ['property_id'], unique=False)
    op.create_index(op.f('ix_competitor_ratings_source'), 'competitor_ratings', ['source'], unique=False)
    op.create_table('cost_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('cost_category', sa.String(length=50), nullable=False),
    sa.Column('amount_per_room_night', sa.Integer(), nullable=False),
    sa.Column('fixed_monthly', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'cost_category', name='uq_cost_setting')
    )
    op.create_index(op.f('ix_cost_settings_property_id'), 'cost_settings', ['property_id'], unique=False)
    op.create_table('daily_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('occupancy_rate', sa.Float(), nullable=False),
    sa.Column('rooms_sold', sa.Integer(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('adr', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=False),
    sa.Column('revpar', sa.Integer(), nullable=False),
    sa.Column('new_bookings', sa.Integer(), nullable=False),
    sa.Column('cancellations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'date', name='uq_perf_property_date')
    )
    op.create_index(op.f('ix_daily_performances_date'), 'daily_performances', ['date'], unique=False)
    op.create_index(op.f('ix_daily_performances_property_id'), 'daily_performances', ['property_id'], unique=False)
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cm_room_type_code', sa.String(length=100), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_product_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_code', name='uq_user_product')
    )
    op.create_index(op.f('ix_user_product_roles_user_id'), 'user_product_roles', ['user_id'], unique=False)
    op.create_table('bar_ladders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=1), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('bar_level', sa.String(length=1), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('available_rooms', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('current_bar_level', sa.String(length=1), nullable=False),
    sa.Column('recommended_bar_level', sa.String(length=1), nullable=False),
    sa.Column('current_price', sa.Integer(), nullable=False),
    sa.Column('recommended_price', sa.Integer(), nullable=False),
    sa.Column('delta_levels', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('modified_bar_level', sa.String(length=1), nullable=True),
    sa.Column('modified_price', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('actioned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_logs')
    op.drop_table('recommendations')
    op.drop_table('pricing_grids')
    op.drop_table('bar_ladders')
    op.drop_index(op.f('ix_user_product_roles_user_id'), table_name='user_product_roles')
    op.drop_table('user_product_roles')
    op.drop_table('room_types')
    op.drop_index(op.f('ix_daily_performances_property_id'), table_name='daily_performances')
    op.drop_index(op.f('ix_daily_performances_date'), table_name='daily_performances')
    op.drop_table('daily_performances')
    op.drop_index(op.f('ix_cost_settings_property_id'), table_name='cost_settings')
    op.drop_table('cost_settings')
    op.drop_index(op.f('ix_competitor_ratings_source'), table_name='competitor_ratings')
    op.drop_index(op.f('ix_competitor_ratings_property_id'), table_name='competitor_ratings')
    op.drop_table('competitor_ratings')
    op.drop_table('competitor_prices')
    op.drop_table('comp_sets')
    op.drop_index(op.f('ix_budget_targets_property_id'), table_name='budget_targets')
    op.drop_table('budget_targets')
    op.drop_index(op.f('ix_booking_snapshots_target_date'), table_name='booking_snapshots')
    op.drop_index(op.f('ix_booking_snapshots_property_id'), table_name='booking_snapshots')
    op.drop_index(op.f('ix_booking_snapshots_capture_date'), table_name='booking_snapshots')
    op.drop_table('booking_snapshots')
    op.drop_table('approval_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('properties')
    op.drop_table('organizations')
    # ### end Alembic commands ###
