"""add_reservations_table

Revision ID: 966d3d0bff2c
Revises: 140b816d43dd
Create Date: 2026-03-25 20:12:06.266453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966d3d0bff2c'
down_revision: Union[str, Sequence[str], None] = '140b816d43dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('reservation_no', sa.String(length=50), nullable=False),
    sa.Column('ota_channel', sa.String(length=50), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_name_kana', sa.String(length=100), nullable=True),
    sa.Column('guest_email', sa.String(length=200), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=10), nullable=True),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'pending', 'cancelled', 'no_show', 'modified', name='reservationstatus'), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_booking_date'), 'reservations', ['booking_date'], unique=False)
    op.create_index(op.f('ix_reservations_checkin_date'), 'reservations', ['checkin_date'], unique=False)
    op.create_index(op.f('ix_reservations_checkout_date'), 'reservations', ['checkout_date'], unique=False)
    op.create_index(op.f('ix_reservations_property_id'), 'reservations', ['property_id'], unique=False)
    op.create_index(op.f('ix_reservations_reservation_no'), 'reservations', ['reservation_no'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reservation_no'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_property_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_checkout_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_checkin_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_booking_date'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
