"""add review inquiry entries

Revision ID: c41a7a4abdd5
Revises: 90b9a82014e4
Create Date: 2026-03-25 19:49:13.905347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41a7a4abdd5'
down_revision: Union[str, Sequence[str], None] = '90b9a82014e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'form', 'phone', name='inquirychannel'), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'resolved', 'closed', name='inquirystatus'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='inquirypriority'), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('inquiry_date', sa.Date(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiry_entries_inquiry_date'), 'inquiry_entries', ['inquiry_date'], unique=False)
    op.create_index(op.f('ix_inquiry_entries_property_id'), 'inquiry_entries', ['property_id'], unique=False)
    op.create_index(op.f('ix_inquiry_entries_status'), 'inquiry_entries', ['status'], unique=False)
    op.create_table('review_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('google', 'rakuten', 'expedia', 'booking', name='reviewplatform'), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('language', sa.Enum('ja', 'en', 'zh', 'ko', 'de', 'other', name='reviewlanguage'), nullable=False),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.Date(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_entries_property_id'), 'review_entries', ['property_id'], unique=False)
    op.create_index(op.f('ix_review_entries_review_date'), 'review_entries', ['review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_entries_review_date'), table_name='review_entries')
    op.drop_index(op.f('ix_review_entries_property_id'), table_name='review_entries')
    op.drop_table('review_entries')
    op.drop_index(op.f('ix_inquiry_entries_status'), table_name='inquiry_entries')
    op.drop_index(op.f('ix_inquiry_entries_property_id'), table_name='inquiry_entries')
    op.drop_index(op.f('ix_inquiry_entries_inquiry_date'), table_name='inquiry_entries')
    op.drop_table('inquiry_entries')
    # ### end Alembic commands ###
